# Generated by Django 5.0.6 on 2024-07-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='contact_no',
            field=models.CharField(default='', max_length=300),
        ),
    ]
